version: "3.9"

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: 3.3.5
    image: react_on_rails_demo_rsc-dev
    command: bash -lc "bin/rails s -b 0.0.0.0 -p 3000"
    env_file: []
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - SHAKAPACKER_DEV_SERVER_HOST=webpack
      - SHAKAPACKER_DEV_SERVER_PORT=3035
      - SHAKAPACKER_DEV_SERVER_PUBLIC=localhost:3035
      - LISTEN_POLLING=true
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
      - rails_tmp:/rails/tmp
      - rails_log:/rails/log
      - rails_storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - webpack
      - webpack-server

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: 3.3.5
    image: react_on_rails_demo_rsc-dev
    command: bash -lc "bin/shakapacker-dev-server"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - SHAKAPACKER_DEV_SERVER_HOST=0.0.0.0
      - SHAKAPACKER_DEV_SERVER_PORT=3035
      - WATCHPACK_POLLING=true
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
      - rails_tmp:/rails/tmp
    ports:
      - "3035:3035"

  webpack-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: 3.3.5
    image: react_on_rails_demo_rsc-dev
    command: bash -lc "SERVER_BUNDLE_ONLY=yes bin/shakapacker --watch"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
      - rails_tmp:/rails/tmp

volumes:
  bundle:
  node_modules:
  rails_tmp:
  rails_log:
  rails_storage:
